---
- name: Increase single body size
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: 'client_max_body_size'
    insertafter: '^http {'
    line: '    client_max_body_size 10m;'
  become: yes

- name: Create directory for static files
  file:
    path: /var/www/wiating/html/images
    state: directory
    mode: '0755'
    owner: root
    group: www-data
  become: yes

- name: Copy site config
  copy:
      src: files/default
      dest: /etc/nginx/conf.d/default.conf
      force: yes
  become: yes
