---
- name: Install pip
  apt:
      state: present
      name: ['build-essential', 'python-dev', 'python3-pip', 'python-setuptools', 'python3-yaml', 'python3-docker']
  become: yes

- name: Install docker_compose module dependencies
  pip:
      name: ['wheel', 'docker-compose']
  become: yes

- name: Add root user to docker group
  user:
    name: root
    groups: docker
    append: yes
  become: yes

- name: Create a directory for docker files
  file:
    path: /opt/elastic
    state: directory
    mode: '0740'
    owner: root
    group: root
  become: yes

- name: Copy docker files to machine
  copy:
      src: elastic/
      dest: /opt/elastic/

- name: Tear down existing services
  docker_compose:
    project_src: /opt/elastic
    state: absent

- name: Create and start services
  docker_compose:
    project_src: /opt/elastic
  register: output

- debug:
    var: output

- name: Run `docker-compose up` again
  docker_compose:
    project_src: /opt/elastic
    build: no
  register: output

- debug:
    var: output

- assert:
    that: "not output.changed "

- name: Stop all services
  docker_compose:
    project_src: /opt/elastic
    build: no
    stopped: yes
  register: output

#- debug:
#    var: output
#
#- assert:
#    that:
#      - "not elasticsearch.elastic_elasticsearch_1.state.running"

- name: Restart services
  docker_compose:
    project_src: /opt/elastic
    build: no
    restarted: yes
  register: output

#- debug:
#    var: output
#
#- assert:
#    that:
#      - "elasticsearch.elastic_elasticsearch_1.state.running"

- name: Wait for port 9200 to become open on the host, don't start checking for 20 seconds
  wait_for:
    port: 9200
    delay: 20
